version: '2'

services:
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      - API_HOST=http://api:9000
      - DATA_HOST=http://data:9090
    networks:
      - reverse-proxy
    links:
      - api:api
      - data:data
    ports:
      - "80:80"
      
  api:
    build: .
    container_name: api
    networks:
      - reverse-proxy
    ports:
      - "9000:9000"
    volumes:
      - ./server:/app/server
    command: bash -c "cd server && node api/app.js"

  data:
    build: .
    container_name: data
    networks:
      - reverse-proxy
    ports:
      - "9090:9090"
    volumes:
      - ./server:/app/server
    command: bash -c "cd server && node data/app.js"

volumes:
  server:

networks:
  reverse-proxy:
    driver: bridge